/*
 * Copyright 2017-2023 VMware, Inc. All Rights Reserved.
 *
 * SPDX-License-Identifier:	Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.vmware.vropsexport.opqsl.console;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.vmware.vropsexport.Metadata;
import com.vmware.vropsexport.models.AdapterKind;
import com.vmware.vropsexport.models.AdapterKindResponse;
import com.vmware.vropsexport.models.StatKeysResponse;
import com.vmware.vropsexport.opsql.console.Completer;
import com.vmware.vropsexport.opsql.console.Parser;
import org.apache.http.HttpException;
import org.jline.reader.Candidate;
import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.junit.Assert;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class CompleterTest {
  private void runTest(final String s, final int cursor, final String... expected)
      throws HttpException, IOException {
    final ObjectMapper om =
        new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    final List<AdapterKind> adapterKinds =
        om.readValue(
                new File("src/test/resources/opsql/AdapterKindResponse.json"),
                AdapterKindResponse.class)
            .getAdapterKind();
    final List<StatKeysResponse.StatKey> statKeys =
        om.readValue(new File("src/test/resources/vmstatkeys.json"), StatKeysResponse.class)
            .getStatKeys();
    final Metadata backend = mock(Metadata.class);
    when(backend.getAdapterKinds()).thenReturn(adapterKinds);
    when(backend.getStatKeysForResourceKind(any(), any())).thenReturn(statKeys);
    final Completer completer = new Completer(backend);
    final LineReader lineReader =
        LineReaderBuilder.builder().completer(completer).parser(new Parser()).build();
    final List<Candidate> candidates = new ArrayList<>();
    completer.complete(lineReader, new Parser().parse(s, cursor), candidates);
    Assert.assertEquals(
        Arrays.stream(expected).collect(Collectors.toList()),
        candidates.stream().map(Candidate::value).collect(Collectors.toList()));
  }

  @Test
  public void testKeywordExpansion() throws HttpException, IOException {
    runTest(
        "res",
        2,
        "resource",
        "name",
        "id",
        "regex",
        "whereStatus",
        "whereHealth",
        "whereState",
        "whereTags",
        "whereProperties",
        "whereMetrics",
        "fields");
  }

  @Test
  public void testMetricExpansion() throws HttpException, IOException {
    runTest(
        "resource(VMWARE:VirtualMachine).fields(cpu",
        41,
        "resource",
        "name",
        "id",
        "regex",
        "whereStatus",
        "whereHealth",
        "whereState",
        "whereTags",
        "whereProperties",
        "whereMetrics",
        "fields",
        "virtualDisk|peak_vDisk_writeLatency",
        "loginsight_generated|total_log_count",
        "mem|capacityRemainingValue_whatif",
        "badge|health_classic",
        "mem|consumer.count_whatif",
        "cpu-alloc|capacityRemainingUsingConsumers",
        "diskspace-total|actual.capacity",
        "mem|capacity.contention_average",
        "cpu|demandmhz",
        "guest|20_sec_peak_disk_queue",
        "cpu-alloc|actual.capacity",
        "mem|guest_nonpageable_estimate",
        "mem|host_demand_for_aggregation",
        "diskspace-total|timeRemaining",
        "mem|zipped_latest",
        "badge|risk_classic",
        "diskspace|poweredOff_whatif",
        "cpu|readiness_average",
        "diskspace|stress_whatif",
        "cpu|capacity.provider.count",
        "mem-alloc|capacityRemaining_min",
        "guest|mem.physUsable_latest",
        "ping|packet_loss|avg",
        "cpu-alloc|idle_whatif",
        "diskspace-total|isStress_whatif",
        "cpu-alloc|stress",
        "diskspace|poweredOff",
        "net|received_average",
        "rescpu|actav1_latest",
        "mem|swapin_average",
        "mem|nonzero_active",
        "net|multicastRx_summation_sum",
        "badge|capacityRemaining",
        "cpu-alloc|size.recommendation",
        "config|cpuAllocation|slotSize",
        "mem-host|actual.capacity_whatif",
        "mem-alloc|actual.capacity_whatif",
        "diskspace|usageWithoutOverhead",
        "OnlineCapacityAnalytics|cpu|capacityRemaining",
        "datastore|numberReadAveraged_average",
        "diskspace|capacityRemainingUsingConsumers_average",
        "cpu-alloc|consumer.count.per.provider.count",
        "cpu|extra_summation",
        "storage|write_average",
        "System Attributes|child_ki_metrics",
        "mem|capacity.provider.count_whatif",
        "summary|running",
        "cpu|poweredOffTimePercent",
        "cpu-alloc|density",
        "sys|vmotionEnabled",
        "OnlineCapacityAnalytics|mem|capacityRemaining",
        "cpu|demandPct",
        "diskspace-alloc|optimal.consumer.per.provider",
        "diskspace|activeNotShared",
        "mem|20_sec_peak_host_contentionPct",
        "cpu|capacityRemainingUsingConsumers_medium",
        "mem-host|consumer.count.per.provider.count_whatif",
        "mem-alloc|poweredOffTimePercent_whatif",
        "diskspace-total|capacity.provider.count",
        "summary|capacityRemainingValue_whatif",
        "mem|timeRemaining",
        "rescpu|runpk1_latest",
        "diskspace-alloc|optimal.consumer.per.provider_whatif",
        "cpu-alloc|capacityRemainingUsingConsumers_medium",
        "mem-host|capacityRemainingUsingConsumers_average",
        "mem-host|capacityRemainingUsingConsumers_small",
        "cpu-alloc|poweredOff",
        "mem-host|capacityRemaining_min",
        "diskspace-total|poweredOffTimePercent",
        "mem-alloc|size.recommendation",
        "diskspace|utilization.range",
        "badge|efficiency_classic",
        "rescpu|runav15_latest",
        "summary|oversized|vcpus",
        "power|power_average",
        "diskspace|idle",
        "sys|productString",
        "guestfilesystem|usage_total",
        "diskspace-alloc|timeRemaining_whatif",
        "sys|poweredOn",
        "OnlineCapacityAnalytics|mem|recommendedSize",
        "mem|consumed_average_mtd",
        "OnlineCapacityAnalytics|mem|capacityRemainingPercentage",
        "mem|host_active",
        "diskspace-total|reason.for.waste",
        "mem|stress_whatif",
        "diskspace|capacity.provider.count_whatif",
        "mem|effective_limit",
        "mem-host|isWaste",
        "OnlineCapacityAnalytics|cpu|recommendedSize",
        "net|broadcastRx_summation_sum",
        "virtualDisk|readIOSize_latest",
        "diskspace-alloc|poweredOffTimePercent_whatif",
        "mem-host|oversized_whatif",
        "mem|oversized",
        "net|packetsRxPerSec",
        "cpu|used_summation",
        "mem|capacityRemainingUsingConsumers_average_whatif",
        "mem-host|timeRemaining_whatif",
        "mem|llSwapOutRate_average",
        "mem-host|capacityRemainingUsingConsumers",
        "OnlineCapacityAnalytics|timeRemainingWithCommit",
        "cpu|stress_whatif",
        "badge|efficiency",
        "diskspace|density",
        "mem|consumed_average_daily",
        "summary|optimal.consumer.per.provider_whatif",
        "mem|decompressionRate_average",
        "mem-alloc|object.demand.with.size.recommendation",
        "summary|capacityRemainingUsingConsumers_medium",
        "diskspace-alloc|oversized",
        "diskspace-alloc|consumer.count.per.provider.count_whatif",
        "disk|usage_capacity",
        "System Attributes|child_all_metrics",
        "rescpu|samplePeriod_latest",
        "mem-alloc|isWaste",
        "diskspace-total|capacityRemainingUsingConsumers_whatif",
        "cpu-alloc|consumer.count.per.provider.count_whatif",
        "power|energy_summation_sum",
        "cpu|demandEntitlementRatio_latest",
        "net|usage_average",
        "diskspace-alloc|poweredOff_whatif",
        "diskspace|actual.capacity.normalized",
        "rescpu|maxLimited1_latest",
        "net|multicastTx_summation_sum",
        "Super Metric|sm_ad36a282-5860-4a11-8e21-16c21e174c67",
        "guest|hugePage.total_latest",
        "virtualDisk|largeSeeks_latest",
        "Super Metric|sm_0e3d6099-d2a3-49b4-8c65-b84aea91e0e7",
        "Super Metric|sm_f7cc0182-6b19-45f5-9f5f-4498393d3e5a",
        "mem-alloc|capacityRemainingUsingConsumers_average",
        "mem-alloc|capacityRemainingValue_whatif",
        "mem|capacityRemainingUsingConsumers_average",
        "Super Metric|sm_03afd277-072e-4409-8979-21f6a3562c71",
        "datastore|commandsAveraged_average",
        "diskspace|used",
        "mem-alloc|capacityRemainingValue",
        "mem|capacity.provider.count",
        "mem-host|capacityRemainingUsingConsumers_medium",
        "rescpu|maxLimited15_latest",
        "diskspace-total|actual.capacity.normalized_whatif",
        "mem|size.recommendation",
        "cpu|corecount_provisioned",
        "diskspace|timeRemaining_whatif",
        "mem|wasteValue50PctInGB",
        "mem-host|consumer.count",
        "diskspace-alloc|capacity.provider.count_whatif",
        "cpu|capacity_demandEntitlementPct",
        "virtualDisk|peak_vDisk_iops",
        "System Attributes|ki_metrics",
        "cpu|20_sec_peak_iowaitPct",
        "disk|write_average",
        "cpu|entitlement_latest",
        "guest|used_memory",
        "diskspace-total|poweredOff_whatif",
        "mem-host|isStress_whatif",
        "cpu|capacityRemainingValue_whatif",
        "diskspace|poweredOffTimePercent_whatif",
        "cpu-alloc|actual.capacity.normalized_whatif",
        "diskspace-alloc|capacityRemainingUsingConsumers",
        "disk|sum_queued_oio",
        "guest|disk_queue",
        "guest|20_sec_peak_contextSwapRate_latest",
        "cpu|consumer.count.per.provider.count",
        "mem-alloc|computed_demand_whatif",
        "mem|isStress_whatif",
        "rescpu|actpk15_latest",
        "mem|poweredOffTimePercent",
        "guest|swap.spaceRemaining_latest",
        "cpu|capacityRemainingUsingConsumers_average_whatif",
        "mem|size.recommendation_whatif",
        "mem-host|capacityRemainingUsingConsumers_large",
        "diskspace|vsanOverhead",
        "guest|mem.free_latest",
        "summary|optimal.consumer.per.provider",
        "summary|number_network",
        "cpu-alloc|capacityRemaining_min",
        "diskspace|capacityRemainingUsingConsumers_small",
        "mem|llSwapInRate_average",
        "mem|guest_activePct",
        "diskspace|actual.capacity_whatif",
        "mem|object.demand.with.size.recommendation",
        "Super Metric|sm_a7c08b4f-ae3c-4a46-b904-1a4e9fe686be",
        "mem-alloc|optimal.consumer.per.provider",
        "net|dropped_sum",
        "mem-host|capacityRemainingUsingConsumers_whatif",
        "mem-host|consumer.count_whatif",
        "summary|metering|partialPrice",
        "net|usage_capacity",
        "disk|numberReadAveraged_average",
        "cpu-alloc|capacityRemainingUsingConsumers_small",
        "summary|isWaste",
        "mem-alloc|oversized",
        "mem-host|capacityRemainingUsingConsumers_average_whatif",
        "cost|monthlyProjectedCost",
        "datastore|maxObserved_NumberWrite",
        "ping|peak_latency",
        "storage|usage_average",
        "diskspace|idle_whatif",
        "Super Metric|sm_c7b28474-211e-4173-8d55-d283ce26f764",
        "mem-alloc|capacityRemainingUsingConsumers_medium",
        "System Attributes|child_active_alarms",
        "virtualDisk|totalWriteLatency_average",
        "cpu|20_sec_peak_overlap_summation",
        "diskspace|snapshot|accessTime",
        "rescpu|actav5_latest",
        "diskspace|oversized_whatif",
        "datastore|maxTotalLatency_latest",
        "net|droppedTx_summation",
        "diskspace-alloc|consumer.count",
        "storage|totalReadLatency_average",
        "cpu-alloc|capacityRemainingValue",
        "mem|optimal.consumer.per.provider",
        "diskspace-alloc|capacityRemaining_whatif",
        "net|demand",
        "mem-alloc|actual.capacity.normalized_whatif",
        "mem|idle_whatif",
        "Super Metric|sm_1186eadc-345c-45d3-9469-67261f902d14",
        "mem|isWaste",
        "cpu-alloc|capacity.provider.count_whatif",
        "diskspace|capacityRemainingUsingConsumers_medium",
        "Super Metric|sm_b4487681-0178-4d4a-9d32-cbaaf5ad423a",
        "cpu|capacityRemainingUsingConsumers_small",
        "diskspace-alloc|size.recommendation",
        "rescpu|runpk5_latest",
        "mem|overheadMax_average",
        "guestfilesystem|percentage",
        "storage|totalLatency_average",
        "cpu|capacityRemaining_min",
        "OnlineCapacityAnalytics|diskspace|capacityRemaining",
        "cpu|usagemhz_average_daily",
        "cpu|size.recommendation_whatif",
        "cpu|object.demand.with.size.recommendation",
        "OnlineCapacityAnalytics|diskspace|recommendedSize",
        "storage_profiles|actualusage",
        "cpu-alloc|capacityRemainingUsingConsumers_average_whatif",
        "guest|disk_queue_latest",
        "cpu|utilization.range",
        "badge|anomaly",
        "net|transmit_demand_average",
        "diskspace-alloc|capacityRemainingUsingConsumers_average",
        "diskspace-total|consumer.count_whatif",
        "cpu|actual.capacity_whatif",
        "mem|capacityRemaining_min_whatif",
        "mem|compressed_average",
        "disk|commandsAborted_summation",
        "diskspace|capacityRemainingUsingConsumers_whatif",
        "cpu|consumer.count",
        "diskspace|capacityRemaining_min_whatif",
        "mem|compressionRate_average",
        "net|dropped",
        "virtualDisk|write_average",
        "mem-alloc|consumer.count_whatif",
        "mem-alloc|actual.capacity.normalized",
        "mem|vmmemctl_average",
        "badge|waste",
        "diskspace-alloc|idle_whatif",
        "Super Metric|sm_bac94c64-ebd3-40a6-992e-7fd1b4d480b4",
        "guestfilesystem|freespace",
        "mem|oversized_whatif",
        "diskspace|timeRemaining",
        "mem-host|density_whatif",
        "cpu|systemSummationPct",
        "summary|capacity.provider.count_whatif",
        "badge|alert_count_info",
        "disk|usage_average",
        "diskspace-total|actual.capacity.normalized",
        "cpu|workload",
        "ping|latency|max",
        "mem|capacityRemaining",
        "diskspace-alloc|actual.capacity.normalized",
        "net|receive_demand_average",
        "cpu|consumer.count.per.provider.count_whatif",
        "cpu|peak_vcpu_usage",
        "net|host_maxObserved_Tx_KBps",
        "diskspace-alloc|waste",
        "net|host_received_average",
        "diskspace-alloc|timeRemaining",
        "disk|commandsAveraged_average",
        "cpu|density_whatif",
        "diskspace-total|capacityRemainingValue",
        "power|energy_summation",
        "disk|max_observed",
        "OnlineCapacityAnalytics|cpu|capacityRemainingPercentage",
        "net|packetsPerSec",
        "rescpu|actpk5_latest",
        "summary|isStress",
        "datastore|usage_average",
        "mem-alloc|idle",
        "virtualDisk|iopsPerGB",
        "summary|undersized|vcpus",
        "hbr|hbrNetRx_average",
        "virtualDisk|numberWriteAveraged_average",
        "Guest OS Services|mkKnownServiceCount",
        "net|droppedPct",
        "diskspace-alloc|oversized_whatif",
        "mem|host_demand_reservation",
        "mem-host|computed_demand_whatif",
        "summary|oversized",
        "cpu-alloc|isStress_whatif",
        "datastore|maxObserved_OIO",
        "net|multicastTx_summation",
        "cpu-alloc|actual.capacity_whatif",
        "diskspace-total|poweredOffTimePercent_whatif",
        "net|20_sec_peak_packetsPerSec",
        "diskspace|size.recommendation",
        "mem|swapoutRate_average",
        "disk|totalReadLatency_average",
        "mem|swapinRate_average",
        "net|host_maxObserved_Rx_KBps",
        "mem|timeRemaining_whatif",
        "rescpu|runpk15_latest",
        "System Attributes|self_alert_count",
        "mem|computed_demand_whatif",
        "summary|consumer.count.per.provider.count",
        "cpu|isStress",
        "cpu|latency_average",
        "System Attributes|alert_count_info",
        "diskspace-total|capacityRemainingUsingConsumers_average_whatif",
        "net|host_maxObserved_KBps",
        "mem-alloc|capacityRemainingUsingConsumers_small",
        "cost|allocation|allocationBasedDailyCpuCost",
        "mem|reason.for.waste",
        "mem|host_usage",
        "summary|mem_shares",
        "diskspace|stress",
        "mem|llSwapUsed_average",
        "net|droppedTx_summation_sum",
        "diskspace-total|isWaste",
        "guestfilesystem|capacity_total",
        "cpu-alloc|density_whatif",
        "cpu-alloc|timeRemaining",
        "diskspace|object.demand.with.size.recommendation",
        "diskspace|oversized",
        "summary|cpu_shares",
        "badge|compliance",
        "datastore|demand",
        "diskspace-alloc|capacityRemainingUsingConsumers_medium",
        "virtualDisk|readLoadMetric_latest",
        "mem|host_contention",
        "datastore|maxObserved_NumberRead",
        "virtualDisk|read_average",
        "cpu-alloc|isStress",
        "cpu|idle_summation",
        "Super Metric|sm_89cd8f91-2bd0-417e-8e2c-c4eeb2200f65",
        "diskspace|computed_demand",
        "diskspace-total|capacityRemainingUsingConsumers",
        "mem|shared_average",
        "guest|20_sec_peak_page.outRate_latest",
        "cpu|oversized_whatif",
        "mem-host|capacityRemainingValue",
        "virtualDisk|writeLoadMetric_latest",
        "cpu|vm_capacity_provisioned",
        "mem|entitlement_average",
        "mem-host|capacityRemainingValue_whatif",
        "badge|timeRemaining",
        "virtualDisk|peak_vDisk_throughput",
        "cpu|timeRemaining",
        "mem-alloc|poweredOffTimePercent",
        "net|pnicBytesRx_average",
        "summary|oversized|potentialMemConsumed",
        "cpu|swapwait_summation",
        "mem-alloc|density_whatif",
        "rescpu|maxLimited5_latest",
        "virtualDisk|20_sec_peak_numberWriteAveraged_average",
        "cpu|optimal.consumer.per.provider",
        "diskspace-alloc|consumer.count.per.provider.count",
        "diskspace-alloc|density_whatif",
        "virtualDisk|commandsAveraged_average",
        "disk|scsiReservationConflicts_summation",
        "diskspace-alloc|capacityRemaining",
        "diskspace-alloc|actual.capacity",
        "mem|actual.capacity_whatif",
        "mem|active_average",
        "guest|mem.standby.reserve_latest",
        "diskspace-total|computed_demand_whatif",
        "mem|density",
        "mem|overheadTouched_average",
        "mem-host|isStress",
        "datastore|oio",
        "guest|mem.standby.normal_latest",
        "diskspace|isStress_whatif",
        "diskspace-alloc|capacityRemaining_min",
        "Guest OS Services|mkInComingConnectionCount",
        "mem-host|capacityRemaining",
        "summary|timeRemaining_whatif",
        "diskspace-total|capacity.provider.count_whatif",
        "mem-host|workload",
        "cpu-alloc|oversized",
        "summary|oversized|memory",
        "mem|host_contentionPct",
        "summary|metering|vmTags|price",
        "virtualDisk|totalLatency",
        "diskspace-alloc|capacityRemainingUsingConsumers_small",
        "diskspace|capacityRemaining_whatif",
        "mem|consumer.count.per.provider.count_whatif",
        "System Attributes|new_ki_alarms",
        "mem-host|optimal.consumer.per.provider",
        "cost|effectiveDailyStorageCost",
        "summary|undersized|potentialMemUsage",
        "cpu|20_sec_peak_swapwaitPct",
        "cpu-alloc|actual.capacity.normalized",
        "cpu|poweredOffTimePercent_whatif",
        "virtualDisk|writeIOSize_latest",
        "diskspace-total|capacityRemaining_whatif",
        "net|broadcastRx_summation",
        "System Attributes|child_new_alarms",
        "cpu-alloc|capacityRemainingValue_whatif",
        "mem-host|consumer.count.per.provider.count",
        "diskspace|capacity.provider.count",
        "cpu|size.recommendation",
        "diskspace-alloc|utilization.range",
        "mem|capacityRemainingUsingConsumers_medium",
        "diskspace-total|capacityRemaining",
        "cpu|capacityRemainingUsingConsumers_large",
        "cpu|isWaste",
        "net|maxObserved_KBps",
        "mem-alloc|consumer.count.per.provider.count_whatif",
        "datastore|totalWriteLatency_average",
        "summary|desktop_status",
        "diskspace|capacityRemaining",
        "Super Metric|sm_740a9494-6935-4e88-aa93-1dea711db0b8",
        "cpu|isStress_whatif",
        "cpu-alloc|capacityRemaining",
        "diskspace|capacityRemainingUsingConsumers_large",
        "mem-host|poweredOff_whatif",
        "storage|numberWriteAveraged_average",
        "System Attributes|new_alarms",
        "diskspace|poweredOffTimePercent",
        "cost|effectiveTotalCost",
        "diskspace|consumer.count.per.provider.count_whatif",
        "mem-alloc|timeRemaining_whatif",
        "cpu|usage_average",
        "mem|reservation_used",
        "mem-alloc|capacityRemaining",
        "System Attributes|change_index",
        "mem-alloc|stress_whatif",
        "mem-alloc|timeRemaining",
        "diskspace|capacityRemainingUsingConsumers_average_whatif",
        "guest|20_sec_peak_cpu_queue",
        "diskspace|consumer.count_whatif",
        "diskspace-total|consumer.count",
        "virtualDisk|readOIO_latest",
        "net|droppedRx_summation",
        "cpu|20_sec_peak_readyPct",
        "datastore|numberWriteAveraged_average",
        "net|transmitted_average",
        "disk|diskdemand",
        "net|packetsTx_summation",
        "net|packetsTxPerSec",
        "net|broadcastTx_summation_sum",
        "mem-host|capacity.provider.count",
        "OnlineCapacityAnalytics|timeRemaining",
        "diskspace|waste",
        "cost|allocation|allocationBasedTotalMTDCost",
        "cpu-alloc|optimal.consumer.per.provider",
        "summary|metering|customProperties|price",
        "badge|risk_state",
        "System Attributes|alert_count_immediate",
        "diskspace-total|capacityRemaining_min_whatif",
        "diskspace-alloc|capacityRemainingUsingConsumers_average_whatif",
        "diskspace|computed_demand_whatif",
        "guest|page.size_latest",
        "badge|stress",
        "datastore|read_average",
        "System Attributes|child_new_ki_alarms",
        "mem-alloc|density",
        "mem|balloonPct",
        "mem|usage_average",
        "summary|idle_whatif",
        "virtualDisk|20_sec_peak_numberReadAveraged_average",
        "diskspace-alloc|isStress",
        "diskspace-alloc|stress_whatif",
        "diskspace-alloc|isStress_whatif",
        "mem|granted_average",
        "mem|zipSaved_latest",
        "mem|activewrite_average",
        "mem|guest_usage",
        "mem|poweredOff",
        "mem-host|actual.capacity.normalized_whatif",
        "mem-host|actual.capacity",
        "diskspace|workload",
        "cpu|capacityRemaining_min_whatif",
        "diskspace-alloc|capacityRemainingValue",
        "summary|metering|sizingPolicy",
        "mem-alloc|capacityRemainingUsingConsumers_whatif",
        "mem|host_demand",
        "cpu|estimated_entitlement",
        "mem-host|stress",
        "datastore|write_average",
        "diskspace-alloc|capacityRemainingUsingConsumers_whatif",
        "cpu|maxlimited_summation",
        "diskspace-total|capacityRemainingUsingConsumers_medium",
        "diskspace-total|capacityRemainingUsingConsumers_average",
        "cpu|computed_demand_whatif",
        "mem-host|actual.capacity.normalized",
        "summary|poweredOffTimePercent",
        "summary|undersized",
        "mem|capacityRemainingUsingConsumers_large",
        "diskspace-total|object.demand.with.size.recommendation",
        "cpu|run_summation",
        "diskspace-total|isStress",
        "cpu-alloc|consumer.count_whatif",
        "summary|capacity.provider.count",
        "cpu|idle_whatif",
        "cpu|capacityRemaining_whatif",
        "storage|commandsAveraged_average",
        "mem-host|capacityRemaining_min_whatif",
        "cost|allocation|allocationBasedDailyMemoryCost",
        "diskspace-total|idle_whatif",
        "mem-alloc|poweredOff",
        "virtualDisk|20_sec_peak_read_average",
        "cpu|idle",
        "cpu|demandOverLimit",
        "datastore|totalLatency_max",
        "mem-host|timeRemaining",
        "cost|allocation|allocationBasedDailyStorageCost",
        "diskspace-total|actual.capacity_whatif",
        "System Attributes|total_alert_count",
        "diskspace-alloc|idle",
        "diskspace-alloc|size.recommendation_whatif",
        "diskspace|capacityRemaining_min",
        "cpu|perCpuCoStopPct",
        "cpu-alloc|capacity.provider.count",
        "diskspace-alloc|object.demand.with.size.recommendation",
        "mem|consumed_average",
        "Guest OS Services|mkUserDefinedServiceCount",
        "badge|health_state",
        "cpu|waste",
        "cost|reclaimableCost",
        "mem-alloc|capacityRemaining_min_whatif",
        "badge|timeRemaining_whatif",
        "mem|capacityRemainingUsingConsumers",
        "mem|zero_average",
        "cpu-alloc|computed_demand_whatif",
        "mem|guest_dynamic_entitlement",
        "ping|packet_loss|max",
        "cpu|poweredOff_whatif",
        "sys|osUptime_latest",
        "diskspace-total|computed_demand",
        "mem-alloc|actual.capacity",
        "performance|number_of_kpis_breached",
        "diskspace-total|poweredOff",
        "net|multicastRx_summation",
        "diskspace-alloc|capacity.provider.count",
        "cpu|costop_summation",
        "badge|risk",
        "mem|capacityRemainingValue",
        "datastore|used",
        "diskspace-total|size.recommendation_whatif",
        "guest|mem.availableToMm_latest",
        "Super Metric|sm_3790bb5b-559d-4f31-a4b1-20e0f79c2c06",
        "cpu|dynamic_entitlement",
        "cpu-alloc|oversized_whatif",
        "diskspace-total|stress_whatif",
        "cpu|capacityRemaining",
        "mem|consumer.count.per.provider.count",
        "disk|numberWriteAveraged_average",
        "disk|totalLatency_average",
        "summary|capacityRemainingUsingConsumers",
        "diskspace-total|workload",
        "cost|monthlyTotalCost",
        "mem|consumedPct",
        "badge|workload",
        "badge|alert_count_critical",
        "cpu|optimal.consumer.per.provider_whatif",
        "cpu|readyPct",
        "cpu|wait_summation",
        "mem|actual.capacity",
        "Super Metric|sm_f2f5ddb2-9050-4afb-ad15-d90c722e2e8b",
        "mem-alloc|consumer.count.per.provider.count",
        "loginsight_generated|error_count",
        "virtualDisk|smallSeeks_latest",
        "diskspace-alloc|actual.capacity_whatif",
        "Super Metric|sm_07528ab4-3fca-4f90-bf3a-c7ec0a70d6a7",
        "cpu-alloc|computed_demand",
        "diskspace-total|utilization.range",
        "badge|density_whatif",
        "mem|capacityRemainingUsingConsumers_whatif",
        "cpu-alloc|capacityRemainingUsingConsumers_whatif",
        "diskspace-alloc|actual.capacity.normalized_whatif",
        "badge|health",
        "guestfilesystem|capacity",
        "guest|mem.activeFileCache_latest",
        "diskspace|optimal.consumer.per.provider",
        "guest|hugePage.size_latest",
        "disk|maxTotalLatency_latest",
        "Guest OS Services|mkServiceCount",
        "summary|capacityRemainingUsingConsumers_average_whatif",
        "rescpu|runav1_latest",
        "storage|demandKBps",
        "diskspace-total|optimal.consumer.per.provider_whatif",
        "cost|demandBasedDailyStorageCost",
        "cpu|actual.capacity.normalized",
        "mem-alloc|capacityRemainingUsingConsumers_average_whatif",
        "diskspace-total|stress",
        "sys|heartbeat_summation",
        "diskspace-total|consumer.count.per.provider.count_whatif",
        "Super Metric|sm_7a8797b4-22af-4848-a121-84a8e9a0183c",
        "config|hardware|thin_Enabled",
        "OnlineCapacityAnalytics|diskspace|capacityRemainingPercentage",
        "summary|poweredOffTimePercent_whatif",
        "diskspace-total|optimal.consumer.per.provider",
        "diskspace-alloc|capacityRemainingValue_whatif",
        "summary|consumer.count",
        "cpu|timeRemaining_whatif",
        "Super Metric|sm_ab378c76-0dce-4c09-ad8d-1c9ff8540882",
        "net|bytesRx_average",
        "storage|read_average",
        "mem|capacityRemaining_min",
        "ping|latency|avg",
        "diskspace-alloc|poweredOff",
        "virtualDisk|mediumSeeks_latest",
        "virtualDisk|actualUsage",
        "mem|capacityRemaining_whatif",
        "mem|demandOverCapacity",
        "virtualDisk|writeOIO_latest",
        "diskspace|consumer.count.per.provider.count",
        "Super Metric|sm_7683bcf3-26c7-4f5e-ac0d-e214d718128a",
        "cpu-alloc|timeRemaining_whatif",
        "virtualDisk|writeLatencyUS_latest",
        "mem|latency_average",
        "mem|waste",
        "mem|density_whatif",
        "mem|consumer.count",
        "diskspace-total|density",
        "summary|availability_kpi",
        "diskspace-alloc|capacityRemainingUsingConsumers_large",
        "loginsight_generated|warning_count",
        "mem-host|density",
        "virtualDisk|busResets_summation",
        "cpu-alloc|capacityRemainingUsingConsumers_average",
        "guest|tools_running_status",
        "cpu-alloc|poweredOff_whatif",
        "cpu|density",
        "diskspace|provisioned",
        "summary|idle",
        "mem|actual.capacity.normalized_whatif",
        "diskspace|actual.capacity",
        "Super Metric|sm_23954c4c-ad9c-45f1-a26c-a07b089c87b3",
        "virtualDisk|20_sec_peak_write_average",
        "badge|stress_whatif",
        "virtualDisk|commandsAborted_summation",
        "mem-alloc|optimal.consumer.per.provider_whatif",
        "guest|mem.needed_latest",
        "datastore|totalLatency_average",
        "disk|diskqueued",
        "mem-alloc|isStress",
        "cpu|capacity.provider.count_whatif",
        "mem-host|object.demand.with.size.recommendation",
        "rescpu|actpk1_latest",
        "mem-alloc|isStress_whatif",
        "OnlineCapacityAnalytics|capacityRemainingPercentage",
        "summary|consumer.count_whatif",
        "mem|vmMemoryDemand",
        "mem-alloc|poweredOff_whatif",
        "summary|undersized|potentialCpuUsage",
        "disk|busResets_summation",
        "ping|peak_packet_loss",
        "badge|density",
        "summary|capacityRemainingUsingConsumers_large",
        "cpu|capacityRemainingUsingConsumers_average",
        "mem-alloc|capacityRemainingUsingConsumers_large",
        "diskspace|consumer.count",
        "ping|packet_loss|min",
        "virtualDisk|20_sec_peak_totalLatency_average",
        "mem-alloc|computed_demand",
        "datastore|maxObserved_Write",
        "mem|swaptarget_average",
        "net|pnicBytesTx_average",
        "System Attributes|child_active_ki_alarms",
        "System Attributes|all_metrics",
        "net|droppedRx_summation_sum",
        "mem|workload",
        "OnlineCapacityAnalytics|mem|timeRemaining",
        "cpu|effective_limit",
        "summary|capacityRemaining_min",
        "summary|capacityRemainingUsingConsumers_average",
        "guestfilesystem|freespace_total",
        "mem-host|capacityRemaining_whatif",
        "Super Metric|sm_8cd1d429-5241-453c-bb7d-21ce0e6d707f",
        "diskspace-total|timeRemaining_whatif",
        "mem|capacityRemainingUsingConsumers_small",
        "summary|metering|metadata|price",
        "cpu|usagemhz_average_mtd",
        "cpu|iowait",
        "mem-host|computed_demand",
        "net|maxObserved_Rx_KBps",
        "diskspace|capacityRemainingValue_whatif",
        "mem-alloc|stress",
        "cpu|usage.vcpus_average",
        "diskspace|snapshot|used",
        "rescpu|actav15_latest",
        "datastore|totalReadLatency_average",
        "mem-host|reason.for.waste",
        "ping|latency|std_dev",
        "mem-host|optimal.consumer.per.provider_whatif",
        "disk|totalWriteLatency_average",
        "cpu|costopPct",
        "cpu|usagemhz_average",
        "cpu-alloc|isWaste",
        "mem|estimated_entitlement",
        "cpu|poweredOff",
        "diskspace|density_whatif",
        "diskspace|diskused",
        "guest|page.inRate_latest",
        "mem|poweredOff_whatif",
        "net|packetsRx_summation_sum",
        "diskspace-total|capacityRemainingValue_whatif",
        "config|hardware|disk_Space",
        "mem-alloc|capacityRemaining_whatif",
        "net|broadcastTx_summation",
        "mem|idle",
        "cpu|overlap_summation",
        "OnlineCapacityAnalytics|cpu|timeRemaining",
        "mem-host|oversized",
        "summary|poweredOff_whatif",
        "System Attributes|alert_count_critical",
        "summary|consumer.count.per.provider.count_whatif",
        "diskspace|snapshot",
        "badge|alert_count_warning",
        "diskspace-total|density_whatif",
        "cpu|actual.capacity.normalized_whatif",
        "cpu|waitPct",
        "cost|detailedAdditionalCost|cost",
        "rescpu|runav5_latest",
        "summary|capacityRemaining_min_whatif",
        "cost|demandBasedDailyCpuCost",
        "diskspace-alloc|capacityRemaining_min_whatif",
        "diskspace-alloc|isWaste",
        "net|maxObserved_Tx_KBps",
        "mem-alloc|consumer.count",
        "cpu|vcpu_usage_disparity",
        "badge|efficiency_state",
        "mem-alloc|waste",
        "mem-alloc|capacity.provider.count",
        "summary|isStress_whatif",
        "summary|metering|memory",
        "summary|poweredOff",
        "cost|effectiveProjectedTotalCost",
        "mem-alloc|idle_whatif",
        "mem-host|capacity.provider.count_whatif",
        "summary|workload_indicator",
        "ping|latency|min",
        "cost|effectiveDailyMemoryCost",
        "cpu|system_summation",
        "ping|packet_loss|std_dev",
        "guest|mem.modifiedPages_latest",
        "cpu-alloc|stress_whatif",
        "badge|fault",
        "mem-alloc|oversized_whatif",
        "mem-host|poweredOffTimePercent_whatif",
        "diskspace|capacityRemainingValue",
        "summary|oversized_whatif",
        "cpu|capacity_contention",
        "cost|dailyAdditionalCost",
        "config|hardware|num_Cpu",
        "disk|diskoio",
        "cpu|consumer.count_whatif",
        "cpu-alloc|poweredOffTimePercent_whatif",
        "mem-host|utilization.range",
        "virtualDisk|readLatencyUS_latest",
        "cpu|20_sec_peak_systemSummationPct",
        "diskspace-total|capacityRemaining_min",
        "summary|capacityRemainingValue",
        "cost|demandBasedDailyMemoryCost",
        "mem-alloc|capacity.provider.count_whatif",
        "mem-host|idle",
        "hbr|hbrNetTx_average",
        "cpu|ready_summation",
        "summary|capacityRemainingUsingConsumers_small",
        "summary|undersized|memory",
        "net|packetsRx_summation",
        "rescpu|sampleCount_latest",
        "cpu|host_demand_for_aggregation",
        "mem|host_nonpageable_estimate",
        "diskspace-total|oversized",
        "guestfilesystem|usage",
        "guest|mem.standby.core_latest",
        "cost|allocation|allocationBasedTotalCost",
        "summary|metering|storage",
        "mem-host|poweredOff",
        "sys|uptime_latest",
        "Super Metric|sm_58d71c2d-8daf-4cef-9538-b16ea6ecf440",
        "mem-host|idle_whatif",
        "mem|swapped_average",
        "badge|alert_count_immediate",
        "cpu-alloc|poweredOffTimePercent",
        "diskspace|perDsUsed",
        "Super Metric|sm_1865d4e2-00e4-4d8c-8ff5-04e084419d73",
        "cpu|stress",
        "cpu-alloc|reason.for.waste",
        "mem|poweredOffTimePercent_whatif",
        "disk|read_average",
        "Super Metric|sm_5c7246d0-f08b-4dba-84f4-30f2bed08aa4",
        "sys|heartbeat_latest",
        "diskspace|optimal.consumer.per.provider_whatif",
        "System Attributes|alert_count_warning",
        "storage|contention",
        "cpu|reason.for.waste",
        "mem|demandOverLimit",
        "diskspace|isStress",
        "mem|host_dynamic_entitlement",
        "badge|capacityRemaining_whatif",
        "diskspace|provisionedSpace",
        "mem|overhead_average",
        "cpu-alloc|size.recommendation_whatif",
        "storage|totalWriteLatency_average",
        "diskspace|actual.capacity.normalized_whatif",
        "cpu|oversized",
        "diskspace-alloc|density",
        "cpu-alloc|object.demand.with.size.recommendation",
        "cpu|20_sec_peak_costopPct",
        "diskspace-alloc|reason.for.waste",
        "cpu|actual.capacity",
        "cpu|capacity_contentionPct",
        "cpu|swapwaitPct",
        "mem|actual.capacity.normalized",
        "mem|computed_demand",
        "virtualDisk|peak_vDisk_readLatency",
        "datastore|maxObserved_Read",
        "mem-host|waste",
        "summary|timeRemaining",
        "cpu-alloc|capacityRemaining_min_whatif",
        "cost|effectiveDailyCost",
        "virtualDisk|totalReadLatency_average",
        "guest|cpu_queue",
        "net|bytesTx_average",
        "storage_profiles|usage",
        "diskspace|reason.for.waste",
        "diskspace-alloc|computed_demand_whatif",
        "cpu|capacityRemainingUsingConsumers",
        "cpu|idlePct",
        "mem|guest_demand",
        "mem-alloc|reason.for.waste",
        "mem|guest_provisioned",
        "mem-alloc|size.recommendation_whatif",
        "summary|snapshotSpace",
        "cpu|demandOverCapacity",
        "mem|isStress",
        "net|host_usage_average",
        "diskspace-alloc|computed_demand",
        "cpu|computed_demand",
        "Guest OS Services|mkOutGoingConnectionCount",
        "mem-host|poweredOffTimePercent",
        "guest|contextSwapRate_latest",
        "diskspace|size.recommendation_whatif",
        "cpu|peak_vcpu_ready",
        "virtualDisk|usage",
        "diskspace-total|size.recommendation",
        "cpu|capacityRemainingUsingConsumers_whatif",
        "diskspace-total|consumer.count.per.provider.count",
        "diskspace-total|waste",
        "cpu-alloc|capacityRemaining_whatif",
        "mem|utilization.range",
        "diskspace-alloc|stress",
        "summary|metering|cpu",
        "cpu-alloc|consumer.count",
        "cost|potentialCostIncrease",
        "summary|utilization.range",
        "summary|capacityRemainingUsingConsumers_whatif",
        "mem-host|stress_whatif",
        "OnlineCapacityAnalytics|diskspace|timeRemaining",
        "net|packetsTx_summation_sum",
        "System Attributes|health",
        "mem-alloc|utilization.range",
        "summary|metering|value",
        "System Attributes|active_alarms",
        "diskspace|capacityRemainingUsingConsumers",
        "diskspace-total|capacityRemainingUsingConsumers_small",
        "net|20_sec_peak_usage_average",
        "diskspace-alloc|consumer.count_whatif",
        "summary|number_datastore",
        "virtualDisk|numberReadAveraged_average",
        "diskspace|isWaste",
        "net|host_transmitted_average",
        "guestfilesystem|percentage_total",
        "cpu|iowaitPct",
        "cpu|capacityRemainingValue",
        "config|memoryAllocation|slotSize",
        "mem-alloc|capacityRemainingUsingConsumers",
        "cpu-alloc|idle",
        "mem|stress",
        "mem|swapout_average",
        "diskspace|notshared",
        "cpu-alloc|capacityRemainingUsingConsumers_large",
        "Super Metric|sm_cd7ee797-83f9-42c8-88ad-41a67f770a43",
        "diskspace-total|oversized_whatif",
        "mem-host|size.recommendation_whatif",
        "cost|effectiveDailyCpuCost",
        "datastore|demand_oio",
        "cpu-alloc|optimal.consumer.per.provider_whatif",
        "diskspace-total|idle",
        "cpu|guaranteed_latest",
        "mem|optimal.consumer.per.provider_whatif",
        "Super Metric|sm_f969e72d-7775-44d7-973a-c92319fcd08b",
        "guest|page.outRate_latest",
        "diskspace-total|capacityRemainingUsingConsumers_large",
        "mem-host|size.recommendation",
        "cpu-alloc|waste",
        "Super Metric|sm_4582a6d7-55f9-4f99-9356-889be516ae11",
        "System Attributes|active_ki_alarms",
        "cpu-alloc|utilization.range",
        "mem|vmmemctltarget_average",
        "Super Metric|sm_825031b6-5bef-435a-8e07-4171234f7a03",
        "summary|metering|additional",
        "cpu|wait",
        "storage|numberReadAveraged_average",
        "virtualDisk|vDiskOIO",
        "System Attributes|availability",
        "Super Metric|sm_abb3de82-b99a-4429-b6aa-958e0a3f2c04",
        "System Attributes|total_alarms",
        "diskspace-alloc|poweredOffTimePercent");
  }
}
